/*
 *  app ble_uuids.h
 */
#ifndef __BLE_UUIDS_H__
#define __BLE_UUIDS_H__

/*
 *  The DWM1001 UUID was generated by the uuidgen utility, which gave
 *      de259bcd-1d7c-48db-a7e3-4759ac03d6b3
 *  The last two hex digits (0xd8, 0x98) were set to 0x00,0x00.
 *      de259bcd-1d7c-48db-a7e3-4759ac030000
 *  This string was reversed to form a byte array to conform to 
 *  Zephyr's BLE API specifications.
 *      000003ac5947-e3a7-db48-7c1d-cd9b25de
 *
 *  DWM1001 UUID Base (common part) are the last 14 bytes of UUID.
 *  The first two bytes will be Service or Characteristic unique values.
 *  This is similar to the UUID16-type UUIDs specified by the BT SIG.
 */
#define DWM1001_UUID_BASE 0x03,0xAC,0x59,0x47,0xE3,0xA7,0xDB,0x48,0x7C,0x1D,0xCD,0x9B,0x25,0xDE

#define DWM1001_UUID_SERVICE            0x00,0x00
#define DWM1001_UUID_NOTIFY             0x01,0x00
#define DWM1001_UUID_COMMAND            0x01,0x00

/*
 *  DWM1001 Service UUID: aa9fa4b1-a1ee-457a-af5b-59a821630000
 */
#define BT_UUID_DWM1001_SERVICE \
    BT_UUID_DECLARE_128(DWM1001_UUID_SERVICE, DWM1001_UUID_BASE)

/*
 *  DWM1001 Characteristics UUIDs: de259bcd-1d7c-48db-a7e3-4759ac03xxxx
 */       
#define BT_UUID_DWM1001_NOTIFY   \
    BT_UUID_DECLARE_128(DWM1001_UUID_NOTIFY, DWM1001_UUID_BASE)

#define BT_UUID_DWM1001_COMMAND   \
    BT_UUID_DECLARE_128(DWM1001_UUID_COMMAND, DWM1001_UUID_BASE)

#endif  // __BLE_UUIDS_H__